name: cost

on:
  schedule:
    - cron: '0 0 * * *' #UTC

jobs:
  cost:
    name: cost
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: 8.1
          extensions: mbstring
          coverage: none
      - name: Install Composer dependencies
        run: composer install --no-dev --no-progress --optimize-autoloader
      - name: Run
        run: php arty feed:json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
