name: feed2json

on:
  push:
  schedule:
    - cron: '0 20 * * *' #UTC

jobs:
  cost:
    name: feed2json
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: 8.3
          extensions: mbstring
          coverage: none
      - name: Install Composer dependencies
        run: composer install --no-dev --no-progress --optimize-autoloader
      - name: Run
        run: php artisan feed:json
        env:
          FILESYSTEM_DISK: ${{ secrets.FILESYSTEM_DRIVER }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
